import type { BiomeGenerationGraph } from './types';

export const DEFAULT_BIOME_GRAPH: BiomeGenerationGraph = {
    id: 'asteroid-valley-default',
    name: 'Asteroid Valley Graph',
    baseBiome: 0,
    noiseSources: {
        continental: { scale: 82, octaves: 4, persistence: 0.52, lacunarity: 2.1, warp: 14 },
        heat: { scale: 54, octaves: 4, persistence: 0.56, lacunarity: 2.0, warp: 9 },
        cave: { scale: 31, octaves: 5, persistence: 0.6, lacunarity: 2.2, warp: 6 },
        lava: { scale: 44, octaves: 4, persistence: 0.58, lacunarity: 2.05, warp: 7 },
        crystal: { scale: 23, octaves: 5, persistence: 0.63, lacunarity: 2.25, warp: 5 },
        erosion: { scale: 96, octaves: 3, persistence: 0.5, lacunarity: 1.9, warp: 12 },
    },
    nodes: [
        {
            id: 'asteroid-to-lava-belts',
            label: 'Asteroid -> Lava Belts',
            from: [0],
            to: 4,
            noise: 'lava',
            min: 0.5,
            max: 1,
            priority: 10,
        },
        {
            id: 'asteroid-to-ruins-zones',
            label: 'Asteroid -> Ruins Zones',
            from: [0],
            to: 5,
            noise: 'erosion',
            min: 0.45,
            max: 0.66,
            priority: 11,
        },
        {
            id: 'asteroid-to-biomass-pockets',
            label: 'Asteroid -> Biomass Pockets',
            from: [0],
            to: 3,
            noise: 'continental',
            min: 0.2,
            max: 0.48,
            priority: 12,
        },
        {
            id: 'asteroid-to-ice-fields',
            label: 'Asteroid -> Ice Fields',
            from: [0],
            to: 2,
            noise: 'heat',
            min: 0,
            max: 0.35,
            priority: 13,
        },
        {
            id: 'asteroid-to-crystal-seams',
            label: 'Asteroid -> Crystal Seams',
            from: [0],
            to: 1,
            noise: 'crystal',
            min: 0.7,
            max: 1,
            priority: 14,
            metadata: {
                crystalType: 'violet-seam',
            },
        },
        {
            id: 'lava-to-cave-shells',
            label: 'Lava -> Cave Shells',
            from: [4],
            to: 6,
            noise: 'cave',
            min: 0.24,
            max: 0.92,
            priority: 20,
        },
        {
            id: 'cave-to-crystal-caves',
            label: 'Cave -> Crystal Caves (Azurite)',
            from: [6],
            to: 7,
            noise: 'crystal',
            min: 0.42,
            max: 1,
            priority: 30,
            metadata: {
                crystalType: 'azurite',
            },
        },
        {
            id: 'lava-to-ice-inclusions',
            label: 'Lava -> Ice Inclusions',
            from: [4],
            to: 2,
            noise: 'cave',
            min: 0.05,
            max: 0.18,
            priority: 31,
        },
        {
            id: 'ruins-to-crystal-veins',
            label: 'Ruins -> Crystal Veins (Amethyst)',
            from: [5],
            to: 7,
            noise: 'crystal',
            min: 0.8,
            max: 1,
            priority: 40,
            metadata: {
                crystalType: 'amethyst',
            },
        },
    ],
};
